use_frameworks! :linkage => :static
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ours-curiosity/CTSpecs'

target 'BaseUIWidget_Example' do
  pod 'CTBaseUIWidget', :path => '../'
end
